Unify caching and fix adjoint tests
dynamiqs/dynamiqs pull request #129
Opened 2023-05-25 16:04 UTC by gautierronan

This PR unifies the way caching is handled by grouping everything inside a generalized `TDTensor` class. This also fixes the adjoint tests that were broken, see https://github.com/pierreguilmin/dynamiqs/issues/128.

This is not super well polished yet, I mostly wanted to see if you guys agreed with the way this is written. If you do I will add back the tests for caching. If not, I'm completely open to other proposals.

2023-05-26 06:38 UTC, gautierronan commented
Here's a second version because I was not happy with the initial one. In the end I used a simple `lru_cache` decorator like @abocquet was proposing initially for the Kraus operators, and for functions that only depend on time, I use the generalized `TDTensor` class. For the issue with caching grad or no_grad tensors, I defined a `clear_cache` function which is called once at the end of every `run_nograd`.

2023-06-05 12:11 UTC, pierreguilmin requested changes
I like the idea!!

2023-06-05 12:11 UTC, pierreguilmin commented on dynamiqs/solvers/solver.py
> +    def clear_cache(self):
This is quite a dangerous way to do what you want, let's keep this for now, I'll propose something cleaner soon.

2023-06-05 12:11 UTC, pierreguilmin commented on dynamiqs/solvers/solver.py
> +                attr.cache_clear()
Why adding this?

2023-06-05 12:11 UTC, pierreguilmin commented on dynamiqs/mesolve/rouchon.py
> +        return sqrt(dt) * self.jump_ops
Actually the Rouchon solver is a fixed time step scheme so `dt` is always the same, we don't need to cache on dt anywhere in this file.

2023-06-09 18:20 UTC, pierreguilmin commented
Replaced by #133.

2023-06-09 18:20 UTC, closed without merging