Add table that summarizes all functions in documentation API
dynamiqs/dynamiqs pull request #152
Opened 2023-06-22 18:24 UTC by gautierronan

(with clickable links that bring to the appropriate function definition)

<img width="1285" alt="Screenshot 2023-06-23 at 13 51 37" src="https://github.com/dynamiqs/dynamiqs/assets/25346881/817b90e9-ecee-4888-9a5c-ea76142f0f24">

2023-07-02 13:31 UTC, pierreguilmin requested changes
IMO this is not how we should document the API. When documenting an API the table of content should follow closely the package structure, as was done before. It's a part of the documentation that is meant for developers, not users. I'm guessing you're copying what's done in PyTorch doc, but it's a very different package with tons of functions (thus they have to structure the API somehow otherwise it's unreadable), but it's not common to do it like this, especially for small packages.

I like the table however, I think it would be better placed in a getting started page "Utils function" which gathers all utils functions we have for a quick lookup.

2023-07-02 13:31 UTC, pierreguilmin commented on docs/templates/python/material/module.html
When copy-pasting templates that you then modify, it'd be nice to have a commit where you just copy-paste the template, and then a subsequent commit where we see what you modify. It's a bit hard to track what is changed here.

2023-07-02 13:31 UTC, pierreguilmin commented on dynamiqs/utils/_wigner.py
I don't think we should perform this move, it's better structured like it was done, and then we can set the API the way we prefer.

2023-07-03 09:44 UTC, gautierronan commented on docs/templates/python/material/module.html
> +        {% endif %}
NB: Here is the modification compared to the copy-pasted file.

2023-07-03 09:45 UTC, gautierronan commented on docs/templates/python/material/module.html
Sorry ! I knew you'd say that but I didn't know how to backtrack through my commits ^^. I essentially just modified lines 58 > 62.

2023-07-03 09:46 UTC, gautierronan commented on dynamiqs/utils/_wigner.py
Yes I completely agree. But how can we make the functions appear on the same page with mkdocs? It seems kinda silly to have a separate page just for a single function `dq.wigner` no?

2023-07-03 09:48 UTC, gautierronan commented
> IMO this is not how we should document the API. When documenting an API the table of content should follow closely the package structure, as was done before. It's a part of the documentation that is meant for developers, not users. I'm guessing you're copying what's done in PyTorch doc, but it's a very different package with tons of functions (thus they have to structure the API somehow otherwise it's unreadable), but it's not common to do it like this, especially for small packages.
I like the table however, I think it would be better placed in a getting started page "Utils function" which gathers all utils functions we have for a quick lookup.

Yes I really like having a table that summarizes all available functions (really missing in the qutip doc IMO). I don't really care where it is, but it should be somewhere. Let's just keep the table implementation in this PR, and think later about how we structure the doc.

2023-07-03 20:20 UTC, pierreguilmin commented on dynamiqs/utils/_wigner.py
No, the API is not a documentation for the user, it's a documentation for the developers, so it should mimic the package structure.

2023-07-03 20:26 UTC, pierreguilmin commented on mkdocs.yml
> +          - Wigner distributions: reference/utils/wigner.md
To be clear, we will make a user-facing documentation with all the titles you propose, but it's not what's typically done for the API documentation.

2023-07-04 09:29 UTC, pierreguilmin approved these changes

2023-07-04 09:33 UTC, merged