Merge `Rouchon1` and `Rouchon1_5`
dynamiqs/dynamiqs pull request #165
Opened 2023-07-13 15:59 UTC by pierreguilmin

2023-07-15 16:52 UTC, abocquet submitted a review, later dismissed

2023-07-19 12:25 UTC, gautierronan requested changes
Nice !

2023-07-19 12:25 UTC, gautierronan commented on dynamiqs/mesolve/mesolve.py
> +        renormalization, ideal for time-independent problems.
```suggestion
        renormalization, ideal for time-independent and/or stiff problems.
```

2023-07-19 12:25 UTC, gautierronan commented on dynamiqs/mesolve/rouchon.py
> +            self.M1srev = sqrt(self.dt) * self.Srev @ self.jump_ops
```suggestion
            self.M1s = sqrt(self.dt) * self.jump_ops @ self.S
            self.M1srev = sqrt(self.dt) * self.jump_ops @ self.Srev
```
Sorry there was a mistake in the previous formula. The S should be on the outside when taking the product \sum_k M_k^\dagger M_k

2023-07-21 09:48 UTC, merged