Add documentation examples to utils
dynamiqs/dynamiqs pull request #183
Opened 2023-07-21 21:21 UTC by pierreguilmin

2023-07-22 08:33 UTC, abocquet approved these changes
Great work!

2023-07-23 08:16 UTC, gautierronan commented
Thanks for writing all this @pierreguilmin ! Did not review the full content yet, but I made a proposal for an alternative examples styling in d9a826160e9a0df1a4f5ecba64949b9d454fa802, the goal being to have a single block of code for each examples section, instead of multiple in a row. It's just a proposal which I personally prefer, but if you don't like it your solution is fine with me too !

<img width="500" alt="Screenshot 2023-07-23 at 10 15 35" src="https://github.com/dynamiqs/dynamiqs/assets/25346881/9149c1ae-cc86-442d-8241-960f05b9f62b">

<img width="500" alt="Screenshot 2023-07-23 at 10 15 39" src="https://github.com/dynamiqs/dynamiqs/assets/25346881/e77c01fd-8f3e-4623-b571-875e98e9dfff">

2023-07-23 08:45 UTC, gautierronan requested changes
Thanks for the PR. Some comments below. Overall I fear some functions are over-documented. I'd be in favor of reducing a bit and going more straight to the point about what the function is doing. This is especially true for simpler functions.

2023-07-23 08:45 UTC, gautierronan commented on dynamiqs/utils/utils.py
> +        tensor([1.000, 1.000])
I think this is overdocumented. It's a simple function, it should have simple documentation.

For instance for the ket part, I think this is already plenty:
```suggestion

    Examples:
        For a ket:
        >>> psi = dq.fock(4, 0) + dq.fock(4, 1)
        >>> dq.norm(psi)
        tensor(1.414)
        >>> psi = dq.unit(psi)
        >>> dq.norm(psi)
        tensor(1.000)
```

2023-07-23 08:45 UTC, gautierronan commented on dynamiqs/utils/utils.py
> +        tensor(True)
You used `all` instead of `torch.all` in the previous function.

2023-07-23 08:45 UTC, gautierronan commented on dynamiqs/utils/utils.py
> +                [-0.025-0.125j, -0.008-0.042j, -0.002-0.007j, -0.001+0.000j]])
Is it necessary to introduce delta, kappa_1 and kappa_phi here? Why not just define directly:
```suggestion
>>> a = dq.destroy(4)
>>> H = a.mH @ a
>>> Ls = torch.stack([a, a.mH @ a])
>>> rho = dq.fock_dm(4, 1)
>>> dq.linbladian(H, Ls, rho)
```
for instance?

2023-07-23 08:45 UTC, gautierronan commented on dynamiqs/utils/utils.py
> +        tensor([[0.-0.j, 1.-0.j, 0.-0.j]])
```suggestion
>>> psi = dq.fock(3, 1)       # shape: (3, 1)
>>> bra = dq.ket_to_bra(Psi)  # shape: (1, 3)
>>> bra == psi.mH
True
```
More straight to the point IMO

2023-07-28 16:01 UTC, pierreguilmin commented
I kept the italic styling, but removed the colors (I think they look better a little dimmed compared to the rest of the documentation). I simplified all the examples, I think you're right they are way too long, and we can something clear in getting started to explain how batching works (its all the same for all functions).

2023-07-28 16:13 UTC, pierreguilmin commented
> PS: For longer examples (more complicated functions), we can also add a <BLANKLINE> to separate the codeblock in two, but still keeping a single code block. This should improve readability.

We can't use <BLANKLINE>, it's a command specific to doctest. I added an example of how to do what you suggest in the documentation of `norm`.

> You used all instead of `torch.all` in the previous function.

Yes you're right, we should use `torch.all` in all examples.

For the suggestion for `ket_to_bra` I like showing how the tensors looks like, to really understand the shape. I think we could add your suggestion but not as an example, rather a note like proposed in the last commit.

2023-07-31 08:44 UTC, gautierronan commented
> and we can something clear in getting started to explain how batching works (its all the same for all functions).

Yes I think having a section on batching, and a section on GPU simulations in Getting Started would be the best way to go about this.

2023-07-31 08:45 UTC, gautierronan approved these changes
Thanks for the corrections I think it's nice like that ! :)

2023-08-01 14:36 UTC, merged