Format doc footer with copyright notice
dynamiqs/dynamiqs pull request #186
Opened 2023-07-24 14:45 UTC by gautierronan

2023-07-24 17:09 UTC, abocquet approved these changes

2023-07-25 10:10 UTC, pierreguilmin requested changes
Nice!

2023-07-25 10:10 UTC, pierreguilmin commented on mkdocs.yml
> +  generator: false
Mmmm, have you read the "Please read this before removing the generator notice" part here > https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=#generator-notice? I think we should either sponsor mkdocs-material, either keep the notice.

2023-07-25 10:10 UTC, pierreguilmin commented on mkdocs.yml
> +copyright: Copyright &copy 2023 dynamiqs
```suggestion
copyright: "&copy Copyright 2023, dynamiqs developers."
```

2023-07-25 10:10 UTC, pierreguilmin commented on mkdocs.yml
> +copyright: Copyright &copy 2023 dynamiqs
To mimic numpy and pytorch docs.

2023-07-25 10:10 UTC, pierreguilmin commented on mkdocs.yml
> +      link: https://dynamiqs-org.slack.com/
We should put the invite link (it redirects automatically if you signed up on the Slack)

https://join.slack.com/t/dynamiqs-org/shared_invite/zt-1z4mw08mo-qDLoNx19JBRtKzXlmlFYLA

2023-07-25 12:10 UTC, pierreguilmin approved these changes

2023-07-25 12:10 UTC, merged