Adjoint method for Euler solver
dynamiqs/dynamiqs pull request #192
Opened 2023-08-17 15:21 UTC by gautierronan

2023-08-18 07:18 UTC, abocquet approved these changes

2023-08-18 17:48 UTC, pierreguilmin requested changes
Nice! Minor comments. It would be nice if you could do a PR for the Schrödinger Euler solver after too.

2023-08-18 17:48 UTC, pierreguilmin commented on dynamiqs/mesolve/euler.py
> +    def backward_augmented(self, t: float, rho: Tensor, phi: Tensor) -> Tensor:
```suggestion
    def backward_augmented(self, t: float, rho: Tensor, phi: Tensor) -> tuple[Tensor, Tensor]:
```
Should also be fixed in `rouchon.py` and `fixed_solver.py`.

2023-08-18 17:48 UTC, pierreguilmin commented on dynamiqs/mesolve/euler.py
> +    def backward_augmented(self, t: float, rho: Tensor, phi: Tensor) -> Tensor:
```suggestion
    def backward_augmented(self, t: float, rho: Tensor, phi: Tensor) -> tuple[Tensor, Tensor]:
```
Should also be fixed in `rouchon.py` and `fixed_solver.py`.

2023-08-18 17:48 UTC, pierreguilmin commented on dynamiqs/mesolve/me_solver.py
> +        """Compute the action of the adjoint Lindbladian on the density matrix.
```suggestion
        """Compute the action of the adjoint Lindbladian on an operator.
```

2023-08-18 17:48 UTC, pierreguilmin commented on dynamiqs/mesolve/me_solver.py
> +    def adjoint_lindbladian(self, t: float, rho: Tensor) -> Tensor:
```suggestion
    def adjoint_lindbladian(self, t: float, x: Tensor) -> Tensor:
```

2023-08-18 17:48 UTC, pierreguilmin requested changes
Nice! Minor comments. It would be nice if you could do a PR for the Schrödinger Euler solver after too.

2023-08-18 17:48 UTC, pierreguilmin commented
Related to #192.

2023-08-18 17:51 UTC, pierreguilmin commented on dynamiqs/mesolve/me_solver.py
> +        out = 1j * self.H_nh(H).mH @ rho + 0.5 * kraus_map(rho, self.jump_ops.mH)
```suggestion
        out = 1j * self.H_nh(H) @ rho + 0.5 * kraus_map(rho, self.jump_ops.mH)
```

2023-09-17 17:42 UTC, gautierronan commented
> It would be nice if you could do a PR for the Schrödinger Euler solver after too.

I realized it's not so simple. Plus I don't expect anyone will every be using that. I don't know, something to think about.

2023-09-17 19:05 UTC, pierreguilmin submitted a review, later dismissed
Very nice 🥳

2023-09-17 19:15 UTC, merged