Add quadrature utilities
dynamiqs/dynamiqs pull request #245
Opened 2023-10-04 15:08 UTC by gautierronan

2023-10-04 15:58 UTC, abocquet submitted a review, later dismissed

2023-10-04 20:42 UTC, pierreguilmin requested changes
Minor comments.

2023-10-04 20:42 UTC, pierreguilmin commented on dynamiqs/utils/operators.py
> +    $a^\dag$ are the annihilation and creation operators respectively.
```suggestion
    It is defined by $x(\phi) = (e^{i\phi} a + e^{-i\phi} a^\dag) / 2$, where $a$ and
    $a^\dag$ are the annihilation and creation operators, respectively.
```
Extreme nit.

2023-10-04 20:42 UTC, pierreguilmin commented on dynamiqs/utils/operators.py
> +    $a^\dag$ are the annihilation and creation operators respectively.
I like the large formulas, I think it's easier to read and captures the eye, but it's as you prefer 😉

2023-10-04 20:42 UTC, pierreguilmin commented on dynamiqs/utils/operators.py
> +                [0.0000e+00+0.0000j, 6.1232e-17-1.0000j, 0.0000e+00+0.0000j]])
I'm pretty sure doctest are not passing here (because it's precision 3 usually).

2023-10-04 20:42 UTC, pierreguilmin commented on dynamiqs/utils/operators.py
> +    r"""Returns the momentum operator $p = i (a - a^\dag) / 2$.
It's `i(a^\dag-a)/2`.

2023-10-05 09:18 UTC, pierreguilmin approved these changes

2023-10-05 09:19 UTC, merged