Add ECD gate
dynamiqs/dynamiqs pull request #271
Opened 2023-10-31 18:23 UTC by pierreguilmin

2023-10-31 18:27 UTC, pierreguilmin commented
@gautierronan a few questions on this one before the review:
- A batch displacement would be very useful (e.g. for multiple seeds for the SNAP and ECD protocols displacement gate), but it's maybe niche so should we keep a separate method `bdisplace` in this file or merge it with `displace` in `dynamiqs.utils.utils`? Note also that it doesn't work with arbitrary batch size like the rest of the library, it requires a 1D tensor of displacement...
- If you see a simpler way to implement the gate (for batched `alpha`) I'm all ~ears~ eyes.

2023-11-02 18:06 UTC, pierreguilmin commented
> It's indeed a bit niche I think. I would say we keep it private for now, and if ever someone asks for it, or it becomes really useful, it'll be simple to make it public.

Agreed, I'm a bit lazy to make it public for now.

>It seems torch.linalg.matrix_exp works with a batch dimension. Maybe you can then write it in a single line without the torch.stack? Actually this may also solve the first question. In this case making it public is less of a debate.

Right, I fixed this. 👍 

> Also, I think the ECD gate is defined as D(beta / 2) |g><g| + D(-beta / 2) |e><e| and not D(beta / 2) |g><e| + D(-beta / 2) |g><e|. See the paper by Campagne-Ibarcq, 2020 Nature. The one by Alec Eickbush might be a typo I think, unless I'm missing something.

They definitions are a bit mixed, let's do the **conditional displacement** gate which corresponds to your formula, I renamed the function for clarity. See appendix of Eickbush paper
![Screenshot 2023-11-02 at 18 59 32](https://github.com/dynamiqs/dynamiqs/assets/38159029/3b4312d3-3700-4eb5-9cca-98aa162e5b9f)

2023-11-03 09:18 UTC, gautierronan requested changes

2023-11-03 09:18 UTC, gautierronan commented on dynamiqs/utils/optimal_control.py
> +        argument `alpha` can be batched, and the returned tensor is batched accordingly.
If `bdisplace` is strictly better than `displace`, I'd be in favor of merging the two and keeping only the batched version but named `displace`. This means we should do the same for `squeeze`, but it's quite straightforward if you want to do it in the same PR.

2023-11-03 10:38 UTC, gautierronan approved these changes
LGTM, thanks for the changes !

2023-11-03 11:03 UTC, merged