[1/?] Split open and closed systems in tests
dynamiqs/dynamiqs pull request #318
Opened 2023-11-10 13:54 UTC by abocquet

2023-11-10 14:28 UTC, gautierronan approved these changes

2023-11-11 09:26 UTC, pierreguilmin commented
Can we wait that I review the PR stack of Ronan's before merging yours @abocquet? I'll review them this afternoon. Cross-merging everything might become a big mess.

2023-11-12 22:15 UTC, gautierronan requested changes
Thanks for the PR. I'm not super satisfied with the idea of adding redundent code (with `_test_batching` both in `ClosedSolverTester` and `OpenSolverTester`). But I don't have much better to propose.

If you have an idea to reduce redudancy, I'd be very happy. Otherwise it LGTM apart from the minor comment below.

2023-11-12 22:15 UTC, gautierronan commented on tests/solver_tester.py
> +from benchmarks.systems.system import ClosedSystem, OpenSystem
Why are you importing from the benchmarks module? It should be independent from the tests. I think you mean to import from `sesolve.closed_system.py` and `mesolve.open_system.py`.

2023-11-13 08:17 UTC, abocquet commented
Thanks for the comment, it was wrong indeed.

As for the redundancy it's less bad (and maybe even better) to have some if it makes the tests easier to read. Let me suggest you https://mtlynch.io/good-developers-bad-tests/ that makes a good point on this issue in general

2023-11-13 12:41 UTC, gautierronan approved these changes

2023-11-13 15:02 UTC, merged