Add Hadamard operator in utils
dynamiqs/dynamiqs pull request #358
Opened 2023-11-24 11:10 UTC by abocquet

2023-11-24 11:26 UTC, gautierronan requested changes
Just a few comments on the doc. Otherwise looks good :)

2023-11-24 11:26 UTC, gautierronan commented on dynamiqs/utils/operators.py
> +    r"""Returns the Hadamard transform on `n` qubits
```suggestion
    r"""Returns the Hadamard transform on `n` qubits.
```

2023-11-24 11:26 UTC, gautierronan commented on dynamiqs/utils/operators.py
> +    $$
```suggestion
    For a single qubit, it is defined by
    $$
        H = \frac{1}{\sqrt2} \begin{pmatrix}
            1 & 1 \\
            1 & -1
        \end{pmatrix}
    $$
    
    For `n` qubits, it is defined by the tensor product of Hadamard matrices: 
    $$
        H_n = \bigotimes_{k=1}^n H
    $$
```

2023-11-24 11:26 UTC, gautierronan commented on dynamiqs/utils/operators.py
> +    $$
A bit more canonical IMO.

2023-11-24 11:26 UTC, gautierronan commented on dynamiqs/utils/operators.py
> +        n: integer number of qubits to act on
```suggestion
        n: Number of qubits to act on.
```

2023-11-24 11:32 UTC, abocquet commented
Solves DYN-130

2023-11-24 12:23 UTC, gautierronan submitted a review, later dismissed

2023-11-24 12:24 UTC, pierreguilmin commented
> Solves DYN-130

You need to put it in the PR description for the linking with linear to work 😉

2023-11-24 12:24 UTC, pierreguilmin commented
I'll try to review this soon.

2023-11-24 14:33 UTC, gautierronan approved these changes

2023-11-26 11:49 UTC, pierreguilmin commented
Loots of very small changes, I dissected them into small commits, mostly conventions, I'll add these to my draft. I removed the `n=0` case, I'm not sure it makes sense to have it. I'll wait for your approval to merge @abocquet 😉

2023-11-26 11:57 UTC, pierreguilmin approved these changes

2023-11-27 08:27 UTC, merged