Refactor mesolve/sesolve
dynamiqs/dynamiqs pull request #404
Opened 2024-01-05 17:31 UTC by gautierronan

2024-01-05 17:32 UTC, pierreguilmin approved these changes

2024-01-05 23:18 UTC, abocquet requested changes

2024-01-05 23:18 UTC, abocquet commented on dynamiqs/sesolve/sesolve.py
> +    gradient: Gradient = Autograd(),
We probably want the gradient to be None by default

2024-01-05 23:18 UTC, abocquet commented
Also `merge_complex` has disappeared, do you assume the next version of diffrax?

2024-01-06 10:15 UTC, abocquet commented on dynamiqs/sesolve/sesolve.py
> +    gradient: Gradient = Autograd(),
Ok it's good

2024-01-06 10:15 UTC, abocquet approved these changes

2024-01-06 10:18 UTC, merged