Document time arrays
dynamiqs/dynamiqs pull request #503
Opened 2024-03-10 00:41 UTC by gautierronan

This PR:

- updates and completes the tutorial on defining time arrays
- adds API documentation for TimeArray objects
- makes various stylistic changes required to document the class attributes and methods

2f9698afcc8a60bc140ff2a49253bea3fafbafd1 and efc5777cbdfa0f7790558ed369c239fbb9075abd are just copy-pasted. I recommand reviewing without these 2 commits.

2024-03-12 12:05 UTC, pierreguilmin requested changes
This is neat. 😍 I've added a bunch of reformulations on top of your commits, happy to discuss anything you want to revert. 😊 I'll propagate the change to the tutorial page if you agree (and finish reviewing the tutorial page).

2024-03-12 13:03 UTC, gautierronan commented on dynamiqs/time_array.py
> +    $\hat O_0$ is a constant array.
Agreed :)

2024-03-12 13:03 UTC, gautierronan commented
LGTM, thanks for the corrections ! Feel free to merge.

2024-03-13 02:44 UTC, pierreguilmin commented
A bunch of other fixes, I'll merge this now @gautierronan (40 commits 🤯), we can iterate on top. It's great, thanks a lot for the work 😍

2024-03-13 02:50 UTC, merged