`__str__` for solvers.py and gradient.py
dynamiqs/dynamiqs pull request #511
Opened 2024-03-14 14:52 UTC by bsaoptima

Implemented feedback

2024-03-14 23:06 UTC, pierreguilmin commented
Replaces #509.

2024-03-15 00:52 UTC, pierreguilmin requested changes
First contribution 🥳 As discussed together, I think we should target something fairly shorter for `__str__`. I suggest
```python
def __str__(self) -> str:
    return eqx.tree_pformat(self, indent=0).replace('\n', '').replace(',', ', ')
```
e.g. for `dq.solver.Dopri5()`:
```python
>>> import dynamiqs as dq
>>> print(dq.solver.Dopri5())
Dopri5(rtol=1e-06, atol=1e-06, safety_factor=0.9, min_factor=0.2, max_factor=5.0, max_steps=100000)
```

You can add this to the `Solver` and `Gradient` base classes then, no need to modify each class 😉

2024-03-15 00:53 UTC, pierreguilmin commented
And then we can probably tweak `Result` to use this instead of just printing the solver and gradient class name (see https://github.com/dynamiqs/dynamiqs/blob/main/dynamiqs/result.py#L75-L78).

2024-03-15 23:36 UTC, pierreguilmin requested changes
Nice! Let's
- Move the implementation to a helper method in `dynamiqs/_utils.py`, e.g. called `tree_str_inline()`.
- Adress this comment > https://github.com/dynamiqs/dynamiqs/pull/511#issuecomment-1998710739.

2024-03-15 23:36 UTC, pierreguilmin commented on dynamiqs/gradient.py
> +        super().__init__()
We don't need this.

2024-03-17 04:54 UTC, pierreguilmin commented
Could we also do the same for options.py, and also print them in results?

2024-03-18 10:33 UTC, bsaoptima commented
forgot to do what you said for `options.py` wait for next push.

2024-03-19 01:43 UTC, pierreguilmin requested changes

2024-03-19 01:43 UTC, pierreguilmin commented on dynamiqs/_utils.py
> +    return eqx.tree_pformat(pytree, indent=0).replace('\n', '').replace(',', ', ')
```suggestion
def tree_str_inline(x: PyTree) -> str:
    return eqx.tree_pformat(x, indent=0).replace('\n', '').replace(',', ', ')
```

2024-03-19 01:43 UTC, pierreguilmin commented on dynamiqs/gradient.py
> +from _utils import tree_str_inline
```suggestion
from ._utils import tree_str_inline
```

2024-03-19 01:43 UTC, pierreguilmin commented on dynamiqs/gradient.py
> +from _utils import tree_str_inline
Same for the other files, to fix
```
ModuleNotFoundError: No module named '_utils'
```

2024-03-19 01:43 UTC, pierreguilmin commented on dynamiqs/sparse.py
I guess you're spoiling a little bit of another PR. 😋

2024-03-19 01:43 UTC, pierreguilmin commented on dynamiqs/result.py
>          }
It does not really look good 😢
```python
import dynamiqs as dq
import jax.numpy as jnp

n = 16
a = dq.destroy(n)
ad = dq.dag(a)

H = 10 * ad @ a
jump_ops = [jnp.sqrt(0.1) * a]
psi0 = dq.coherent(n, 1.0)
tsave = jnp.linspace(0, 1.0, 101)
gradient = dq.gradient.Autograd()
result = dq.mesolve(H, jump_ops, psi0, tsave, gradient=gradient)
print(result)
```

```
==== Result ====
Solver  : Tsit5(rtol=f32[], atol=f32[], safety_factor=f32[], min_factor=f32[], max_factor=f32[], max_steps=i32[])
Gradient: Autograd()
States  : Array complex64 (101, 16, 16) | 202.00 Kb
Infos   : 67 steps (67 accepted, 0 rejected)
Options : Options(save_states=bool[], verbose=bool[], cartesian_batching=bool[], t0=None, save_extra=None)
```

I think the reason is that for the JIT every int/bool is converted to a single-element JAX array 😬

For now I propose to keep the old result code, and we can think about a fix in another PR.

2024-03-31 09:02 UTC, pierreguilmin approved these changes
I've fixed the remaining bits. Thanks @bsaoptima!

2024-03-31 09:09 UTC, pierreguilmin approved these changes

2024-03-31 09:09 UTC, merged