add test functions for add, sub, mul
dynamiqs/dynamiqs pull request #583
Opened 2024-05-17 14:04 UTC by bsaoptima

This PR is to add the test functions for the base methods we currently have implemented for `__add__`,  `__sub__` and ` `__mul__` in the SparseQArray class.

There was a small debate regarding if the base is `bagrici/utility-sparse` or `bagrici/base-sparse`, I think the former is the best choice since the tests depend on the `to_sparse` and `to_dense` utility functions. That way we can merge and then merge again on `bagrici/base-sparse`.

2024-05-27 12:29 UTC, gautierronan requested changes
A few small comments, mainly regarding the test matrix definitions. Otherwise it LGTM.

2024-05-27 12:29 UTC, gautierronan commented on tests/test_sparse.py
> +        N = 4
I would be tempted to set `N` to slightly larger than `4` to make sure we are not lucky. Something like 6 or 10 should be plenty.

2024-05-27 12:29 UTC, gautierronan commented on tests/test_sparse.py
> +    def test_transform(self, rtol=1e-05, atol=1e-08):
```suggestion
    def test_convert(self, rtol=1e-05, atol=1e-08):
```
(this test function should appear either after `test_mul` or before `test_add`)

2024-06-05 21:00 UTC, gautierronan commented on tests/test_sparse.py
> +        offsets = tuple(range(-(num_diags // 2), (num_diags // 2) + 1))
As we discussed, I think there's a mismatch between `num_diags` and the size of `offsets`. Once this is fixed, it's good to go for me.

2024-06-19 11:08 UTC, pierreguilmin approved these changes

2024-06-21 08:35 UTC, merged