Add basic properties to `SparseQArray`
dynamiqs/dynamiqs pull request #585
Opened 2024-05-17 15:31 UTC by bsaoptima

Adding the basic properties to `SparseQArray`:

- `shape`
- `ndim`
- `mT`

2024-05-27 12:32 UTC, gautierronan commented
From the RFC, I think this PR should add:
 - `dtype`
 - `shape`
 - `ndim`
 - `conj`
 - `dag`
 - `norm`
 - `unit`
 - `reshape`
 - `broadcast_to`
 - `ptrace` (this one is not easy, either we do it in a separate PR, or we convert to dense and call `dq.ptrace` in the appropriate way)

2024-06-05 20:52 UTC, gautierronan requested changes
Two minor comments, otherwise it's good.

2024-06-05 20:52 UTC, gautierronan commented on dynamiqs/sparse.py
> +        return self.diags.shape
The shape of the matrix is not the shape of `self.diags`, it's (N, N).

2024-06-05 20:52 UTC, gautierronan commented on dynamiqs/sparse.py
> +        N = self.dims[0]
Should be `shape` here, not `dims`.

2024-06-19 11:09 UTC, pierreguilmin approved these changes

2024-06-21 08:54 UTC, merged