Specify `PWCTimeArray` discontinuities in diffrax solver
dynamiqs/dynamiqs pull request #600
Opened 2024-06-07 03:30 UTC by pierreguilmin

Related to DYN-218.

Note that this PR breaks the JIT. The reason is that `jnp.unique` is data-dependent, see doc here > https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.unique.html. We have three solutions:
- Either `jump_ts` does not need to be unique, that would be ideal.
- Otherwise we need to specify statically the `size` argument of `jnp.unique`, which is fine if the `H`, `jump_ops` are defined outside JIT, we can just feed `len(times)`.
- Otherwise we could specify a default `size` to `jnp.unique` (specifically made for this purpose), but then we need to pick a `fill_value`, and we need to check what fits Diffrax.

2024-06-07 03:41 UTC, pierreguilmin commented
I'm also thinking, for the propagator solver to work with PWC pulse ([DYN-47](https://linear.app/dynamiqs/issue/DYN-47/use-pwc-hamiltonian-format-in-propagator-solvers)), we'll probably need this uniquely sorted time-array anyway.

2024-06-07 09:37 UTC, pierreguilmin commented
Turns out the easy solution works, thanks @gautierronan for looking into this!
> 1. Either jump_ts in Diffrax does not need an array with unique values, that would be ideal.

2024-06-09 14:26 UTC, gautierronan requested changes
Just a single comment: I think we need to sort the `discontinuity_ts` array somewhere inside the `time_array.py` file. Right now, I believe we can pass an unsorted array and it will never be sorted if `sesolve` is used. For `mesolve`, it goes through `_concatenate_sort` so its fine.

The rest looks good to me!

2024-06-09 14:26 UTC, gautierronan commented on dynamiqs/time_array.py
> +            necessarily contain unique values).
Related to the main comment. I don't think the array is necesseraly sorted at this point.

2024-06-12 01:52 UTC, pierreguilmin commented
> Just a single comment: I think we need to sort the discontinuity_ts array somewhere inside the time_array.py file.

Good catch!!

2024-06-12 01:59 UTC, merged