Move rand_* to dq.rand.*
dynamiqs/dynamiqs pull request #664
Opened 2024-08-02 16:30 UTC by abocquet

Closes https://linear.app/dynamiqs/issue/DYN-232/move-dqrand-to-dqrand

2024-08-05 09:35 UTC, pierreguilmin requested changes
Can we reverse the naming `dq.rand.imag` to `dq.rand.complex`? I read `imag` as imaginary part at first, similar to `x.real`, `x.imag`, or *imaginary number*.

2024-08-05 10:41 UTC, abocquet commented
Unfortunately `complex` is a reserved keyword of python, so I had to come up with something else. I get your point though, and any better name is welcome

2024-08-06 12:11 UTC, pierreguilmin approved these changes

2024-08-06 12:15 UTC, pierreguilmin commented
Great 😁

2024-08-06 12:19 UTC, merged