Adapt task doctest to different OS
dynamiqs/dynamiqs pull request #743
Opened 2024-10-03 08:03 UTC by vaicecaze

2024-10-04 15:28 UTC, gautierronan commented
Hi @vaicecaze, thanks for fixing this. Instead of adding a file, I would suggest the following fix that only uses shell script:
```shell
cmd = '''
  echo "\n>>> pytest dynamiqs" &&
  case "$OSTYPE" in
    linux*|darwin*|solaris*) rm -f docs/figs_code/*.{png,gif} ;;
    msys*|cygwin*|win32*)    del /Q docs\\figs_code\\*.png docs\\figs_code\\*.gif ;;
    *)                       echo "Unknown OS: $OSTYPE" && exit 1 ;;
  esac &&
  pytest dynamiqs
'''
```
It seems to work on macOS, I'll let you check if that also works under Windows.

2024-10-09 07:39 UTC, vaicecaze commented
Hi @gautierronan,
Thanks for your reply!
'case' is not recognized on Windows so I adapted again the code to the OS. I removed end-of-line '\n' characters as they appear as invalid. Hope it also works on macOS.

2024-10-10 13:38 UTC, pierreguilmin commented
> It doesn't seem to be working on linux unfortunately. I'm not sure how to fix this in a clean way TBH.

I think the original solution was ok (with the Python script). We should strive to support all development platforms.

> Also, @pierreguilmin, why do we need this rm call?

Otherwise if the doctest fails the doc figures are not updated and come from the latest run of the doc (e.g. btw two branches), which is quite confusing.

2024-10-10 15:08 UTC, gautierronan commented
> I think the original solution was ok (with the Python script). We should strive to support all development platforms.

Alright, I'm fine either way, let's go back to the original solution then. Because the python script is to remove documentation files, maybe we can put this `remove_file.py` somewhere inside `docs/` to not clutter the main directory.

2024-10-11 12:36 UTC, vaicecaze commented
Hi @gautierronan!
I just reverted to commit 902d900a7ff7baf28beb6526059c10ada5a80507 with the remove_files.py method and moved it to docs/ folder. Tell me if it's okay for you.

2024-10-11 12:49 UTC, gautierronan requested changes
Apart from the small typo below, if the CI passes, then it's good for me!

2024-10-11 12:49 UTC, gautierronan commented on pyproject.toml
> +cmd = 'echo "\n>>> pytest docs" && rm python docs/remove_files.py && pytest docs'
```suggestion
cmd = 'echo "\n>>> pytest docs" && python docs/remove_files.py && pytest docs'
```
(typo)

2024-10-11 12:50 UTC, gautierronan commented on docs/remove_files.py
> +def remove_files(pattern: ArrayLike):
```suggestion
def remove_files(pattern: str):
```
And this should be a string I guess?

2024-10-11 12:51 UTC, gautierronan submitted a review, later dismissed
Thanks @vaicecaze!

2024-10-11 13:16 UTC, gautierronan approved these changes

2024-10-11 13:16 UTC, merged