Add thermal_dm() state method
dynamiqs/dynamiqs pull request #744
Opened 2024-10-04 07:56 UTC by vaicecaze

Removed remove_files.py file in this PR because of compatibility issues with tests

2024-10-20 10:11 UTC, pierreguilmin commented
I think this stills needs a bit more work, am I right? If you need anything from our side @vaicecaze don't hesitate to ask. Otherwise there's no rush, it's just to ensure you're not stuck somewhere. 😊

2024-10-28 09:05 UTC, pierreguilmin requested changes
I've added a commit with a few fixes on top. @vaicecaze:
- the return should be complex
- `dq.thermal_dm(4, [0.1, 0.2, 0.3])` raises an exception, it should return an array of shape `(3, 4, 4)`

2025-06-04 12:18 UTC, gautierronan submitted a review, later dismissed

2025-06-04 12:33 UTC, pierreguilmin commented
Great, thanks a lot @gautierronan!

2025-06-04 12:34 UTC, merged