Document qarray
dynamiqs/dynamiqs pull request #802
Opened 2024-11-21 16:14 UTC by pierreguilmin

First version of the documentation.

2024-11-21 17:58 UTC, gautierronan requested changes

2024-11-21 17:58 UTC, gautierronan commented on dynamiqs/qarrays/qarray.py
> +    Note-: Shortcuts methods to use quantum utilities
I think this note and its table are quite important (equally to the rest of the docstring IMO). I would propose not having it as a note. This is what PyTorch does for instance, [here](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.mH).

Actually, I would even go further and provide a table for the _all_ methods of a `dq.QArray`, such that:

- for methods that are duplicates of quantum utilities (e.g. `.dag()`), just have a description saying "See `dq.this`" or "Alias of `dq.this`" (like pytorch does)
- for methods that are new to QArrays (e.g. `.conj()` or `reshape(*shape)`), have a short one-liner description + link to the full docstring just below in the page.

2024-11-21 17:58 UTC, gautierronan commented on dynamiqs/qarrays/qarray.py
> +        `dq.isdag(x)`. Here is the complete list of these shortcuts:
```suggestion
        `dq.dag(x)`. Here is the complete list of these shortcuts:
```
typo

2024-11-27 10:36 UTC, pierreguilmin commented
@gautierronan if you agree with the overall content I propose to merge this and iterate on top later for styling / minor modifications.

2024-11-27 14:59 UTC, gautierronan approved these changes
LGTM!

2024-11-27 14:59 UTC, merged