Add a solver for the diffusive stochastic master equation (SME)
dynamiqs/dynamiqs pull request #877
Opened 2024-12-26 21:23 UTC by pierreguilmin

Finally. 🙈

See old PR https://github.com/dynamiqs/dynamiqs/pull/548.

Follow-up task: https://linear.app/dynamiqs/issue/DYN-196/improve-dqdsmesolve.

⚠️ This should be merged, not stashed.

2025-01-22 11:12 UTC, gautierronan commented on docs/documentation/advanced_examples/monitored-oscillator.md
> +# Continuous measurement of an oscillator
I think these two tutorials are great as is, but I would suggest merging them into a single "Continuous measurement" tutorial with two main sections (Oscillator and Qubit) since they explain exactly the same thing simply on two different systems.

2025-01-24 07:04 UTC, pierreguilmin commented on dynamiqs/integrators/apis/dsmesolve.py
> +    etas = etas[etas != 0]
Yes!

2025-01-24 07:05 UTC, pierreguilmin commented on dynamiqs/integrators/apis/dsmesolve.py
> +    tsave = tuple(tsave.tolist())  # todo: fix static tsave
Because we do a `jax.lax.scan`. We could also use the while loops of equinox, but I couldn't make it as fast. Anyway, I hope that we can fall back to Diffrax solvers in not too long, once the performance issue has been fixed.

2025-01-24 07:07 UTC, pierreguilmin commented on dynamiqs/integrators/apis/dsmesolve.py
> +    f = jax.vmap(f, in_axes, out_axes)
For now the keys are shared for all batch, it's much simpler to document. There is an item in the issue for the extension you're mentioning, but we should discuss whether we really want to do this or not.
> " 🚀 support different keys for different batch, or broadcast-compatible keys etc."

2025-01-24 07:08 UTC, pierreguilmin commented on dynamiqs/integrators/apis/dsmesolve.py
> +    integrator_constructor = dsmesolve_integrator_constructor
Yes, I've fixed a little bit to exactly mirror the other solvers structure, we will add other options here this year.

2025-01-24 07:08 UTC, pierreguilmin commented on dynamiqs/integrators/apis/dsmesolve.py
> +            ' consider using `dq.sesolve()` to solve the Schrödinger equation.'
Why?

2025-01-24 07:10 UTC, pierreguilmin commented on dynamiqs/integrators/core/fixed_step_integrator.py
> +            raise ValueError('Option `t0` is invalid for fixed step SME solvers.')
No because you need to integrate from `t0` to the first time of `tsave`, and we only only support fixed-step for now, I edited the issue:
```
- 🚀 support non-linearly spaced tsave (potentially with times not matching the dt, and we have to step exactly to these times)
- 🚀 support non-linearly spaced tsave (potentially with times not matching the dt, and we have to step exactly to these times) and `options.t0`
```

2025-01-24 07:15 UTC, pierreguilmin commented on dynamiqs/integrators/core/fixed_step_integrator.py
> +        nsteps_per_chunk = 1000
I don't think we want to let the user tune this, it doesn't change anything (speed and memory wise) if `100 <= nsteps_per_chunk <= 10_000`, but choosing the value below 100 will slow-down the code, and choices above will bloat the memory. So `1000` is a magic number but there's no reason to choose another one, I think we should keep it a backend implementation trick rather than complicate the `EulerMaruyama` solver.

2025-01-24 07:29 UTC, pierreguilmin commented
![Screenshot 2025-01-24 at 12 58 46](https://github.com/user-attachments/assets/330ee8eb-f1d8-426f-9cc4-cfbc52ca54c8)

To allow more WIP tutorials, for or against? 😋

2025-01-24 12:52 UTC, gautierronan requested changes
Thanks for all the fixes! I have one last comment, otherwise everything LGTM!

2025-01-24 12:52 UTC, gautierronan commented on docs/documentation/advanced_examples/diffusive-sme.md
> +# Diffusive SME
```suggestion
# Weak diffusive measurements
```
or
```suggestion
# Continuous measurements
```
I don't think the tutorial should take the name of an equation. In advanced examples, we want to show how to achieve some simulation of quantum physics: the equation is the means to do it, but the end goal is the continuous measurement.

2025-01-24 12:55 UTC, gautierronan commented
> To allow more WIP tutorials, for or against? 😋

I think we should not consider this WIP, and we're setting too high of a standard for these tutorials. IMO the tutorial you've already written is extremely useful already, and doesn't look like a draft. Yes, it could be improved here and there, but it's already plenty for what most users are looking for.

2025-01-24 12:57 UTC, gautierronan commented on dynamiqs/integrators/apis/dsmesolve.py
> +    f = jax.vmap(f, in_axes, out_axes)
Ok, I definitely think we should handle batching over keys in the exact same way as all other batched items. But ok to keep it like that for now.

2025-01-24 12:57 UTC, gautierronan commented on dynamiqs/integrators/apis/dsmesolve.py
> +    integrator_constructor = dsmesolve_integrator_constructor
Thanks!

2025-01-24 12:58 UTC, gautierronan commented on dynamiqs/integrators/core/fixed_step_integrator.py
> +            raise ValueError('Option `t0` is invalid for fixed step SME solvers.')
Hmmm, ok!

2025-01-24 12:59 UTC, gautierronan commented on dynamiqs/integrators/core/fixed_step_integrator.py
> +        nsteps_per_chunk = 1000
Ok, indeed if you're sure it's the only useful value, then we don't have to make it public. But how about when the Hilbert space is very large, and we can't store `1000` iterations in memory?

2025-01-24 13:04 UTC, pierreguilmin commented on dynamiqs/integrators/core/fixed_step_integrator.py
> +        nsteps_per_chunk = 1000
We don't store them, it's a `jax.lax.scan`. It's just that we generate random numbers by chunks (1000 at once).

2025-01-24 13:23 UTC, gautierronan commented on docs/documentation/advanced_examples/continuous-diffusive-measurement.md
> +    This tutorial is under construction, this is a draft version.
Do you want to remove this? Or we merge in current state?

2025-01-24 13:25 UTC, pierreguilmin commented on docs/documentation/advanced_examples/continuous-diffusive-measurement.md
> +    This tutorial is under construction, this is a draft version.
I'd like to keep it for now, as some aspects of the tutorial are not very rigorous.

2025-01-24 15:23 UTC, gautierronan approved these changes

2025-01-24 15:23 UTC, merged